config/routes.rb
RailsTemplate::Application.routes.draw do
  #get '/', :controller => 'home', :action => 'index'
  get "search_result", :controller => 'home', :action => 'search_result'
  get "home/index"

  resources :user_restaurant_configs

  resources :users

  resources :search_keys

  resources :restaurants

  resources :frequent_sets

  resources :foods

  root :to => 'home#index' 
end

app/models/user_restaurant_config.rb
class UserRestaurantConfig < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/user_restaurant_configs_controller.rb
class UserRestaurantConfigsController < ApplicationController
  # GET /user_restaurant_configs
  # GET /user_restaurant_configs.json
  def index
    @user_restaurant_configs = UserRestaurantConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_restaurant_configs }
    end
  end

  # GET /user_restaurant_configs/1
  # GET /user_restaurant_configs/1.json
  def show
    @user_restaurant_config = UserRestaurantConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_restaurant_config }
    end
  end

  # GET /user_restaurant_configs/new
  # GET /user_restaurant_configs/new.json
  def new
    @user_restaurant_config = UserRestaurantConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_restaurant_config }
    end
  end

  # GET /user_restaurant_configs/1/edit
  def edit
    @user_restaurant_config = UserRestaurantConfig.find(params[:id])
  end

  # POST /user_restaurant_configs
  # POST /user_restaurant_configs.json
  def create
    @user_restaurant_config = UserRestaurantConfig.new(params[:user_restaurant_config])

    respond_to do |format|
      if @user_restaurant_config.save
        format.html { redirect_to @user_restaurant_config, notice: 'User restaurant config was successfully created.' }
        format.json { render json: @user_restaurant_config, status: :created, location: @user_restaurant_config }
      else
        format.html { render action: "new" }
        format.json { render json: @user_restaurant_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_restaurant_configs/1
  # PUT /user_restaurant_configs/1.json
  def update
    @user_restaurant_config = UserRestaurantConfig.find(params[:id])

    respond_to do |format|
      if @user_restaurant_config.update_attributes(params[:user_restaurant_config])
        format.html { redirect_to @user_restaurant_config, notice: 'User restaurant config was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_restaurant_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_restaurant_configs/1
  # DELETE /user_restaurant_configs/1.json
  def destroy
    @user_restaurant_config = UserRestaurantConfig.find(params[:id])
    @user_restaurant_config.destroy

    respond_to do |format|
      format.html { redirect_to user_restaurant_configs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/user_restaurant_configs_helper.rb
module UserRestaurantConfigsHelper
end

app/views/user_restaurant_configs/_form.html.haml
= form_for @user_restaurant_config do |f|
  - if @user_restaurant_config.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_restaurant_config.errors.count, "error")} prohibited this user_restaurant_config from being saved:"
      %ul
        - @user_restaurant_config.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :restaurant_id
    = f.number_field :restaurant_id
  .field
    = f.label :score
    = f.number_field :score
  .field
    = f.label :commet
    = f.text_area :commet
  .actions
    = f.submit 'Save'

app/views/user_restaurant_configs/edit.html.haml
%h1 Editing user_restaurant_config

= render 'form'

= link_to 'Show', @user_restaurant_config
\|
= link_to 'Back', user_restaurant_configs_path

app/views/user_restaurant_configs/index.html.haml
%h1 Listing user_restaurant_configs

%table
  %tr
    %th User
    %th Restaurant
    %th Score
    %th Commet
    %th
    %th
    %th

  - @user_restaurant_configs.each do |user_restaurant_config|
    %tr
      %td= user_restaurant_config.user_id
      %td= user_restaurant_config.restaurant_id
      %td= user_restaurant_config.score
      %td= user_restaurant_config.commet
      %td= link_to 'Show', user_restaurant_config
      %td= link_to 'Edit', edit_user_restaurant_config_path(user_restaurant_config)
      %td= link_to 'Destroy', user_restaurant_config, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User restaurant config', new_user_restaurant_config_path

app/views/user_restaurant_configs/new.html.haml
%h1 New user_restaurant_config

= render 'form'

= link_to 'Back', user_restaurant_configs_path

app/views/user_restaurant_configs/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_restaurant_config.user_id
%p
  %b Restaurant:
  = @user_restaurant_config.restaurant_id
%p
  %b Score:
  = @user_restaurant_config.score
%p
  %b Commet:
  = @user_restaurant_config.commet

= link_to 'Edit', edit_user_restaurant_config_path(@user_restaurant_config)
\|
= link_to 'Back', user_restaurant_configs_path