config/routes.rb
RailsTemplate::Application.routes.draw do
  #get '/', :controller => 'home', :action => 'index'
  get "search_result", :controller => 'home', :action => 'search_result'
  get "home/index"

  resources :user_restaurant_configs

  resources :users

  resources :search_keys

  resources :restaurants

  resources :frequent_sets

  resources :foods

  root :to => 'home#index' 
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :ok }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.haml
= form_for @food do |f|
  - if @food.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      %ul
        - @food.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :recommend_time
    = f.number_field :recommend_time
  .field
    = f.label :food_url
    = f.text_field :food_url
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :restaurant_id
    = f.number_field :restaurant_id
  .actions
    = f.submit 'Save'

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/index.html.haml
%h1 Listing foods

%table
  %tr
    %th Name
    %th Price
    %th Recommend time
    %th Food url
    %th Image url
    %th Restaurant
    %th
    %th
    %th

  - @foods.each do |food|
    %tr
      %td= food.name
      %td= food.price
      %td= food.recommend_time
      %td= food.food_url
      %td= food.image_url
      %td= food.restaurant_id
      %td= link_to 'Show', food
      %td= link_to 'Edit', edit_food_path(food)
      %td= link_to 'Destroy', food, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Food', new_food_path

app/views/foods/new.html.haml
%h1 New food

= render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @food.name
%p
  %b Price:
  = @food.price
%p
  %b Recommend time:
  = @food.recommend_time
%p
  %b Food url:
  = @food.food_url
%p
  %b Image url:
  = @food.image_url
%p
  %b Restaurant:
  = @food.restaurant_id

= link_to 'Edit', edit_food_path(@food)
\|
= link_to 'Back', foods_path